# Generated by Django 5.1.1 on 2024-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menshirt',
            options={'verbose_name': 'Мужские рубашки'},
        ),
        migrations.AlterModelOptions(
            name='menshoes',
            options={'verbose_name': 'Мужская обувь'},
        ),
        migrations.AlterModelOptions(
            name='mentrousers',
            options={'verbose_name': 'Мужские брюки/джинсы'},
        ),
        migrations.AlterModelOptions(
            name='mentshirt',
            options={'verbose_name': 'Мужские футболки'},
        ),
        migrations.AlterModelOptions(
            name='womendressblouse',
            options={'verbose_name': 'Женские платья/блузки'},
        ),
        migrations.AlterModelOptions(
            name='womenshoes',
            options={'verbose_name': 'Женская обувь'},
        ),
        migrations.AlterModelOptions(
            name='womentrousers',
            options={'verbose_name': 'Женские брюки/джинсы'},
        ),
        migrations.AlterModelOptions(
            name='womentshirt',
            options={'verbose_name': 'Женские футболки'},
        ),
        migrations.AddField(
            model_name='mentrousers',
            name='eur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Европа'),
        ),
        migrations.AddField(
            model_name='mentrousers',
            name='height_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рост (см)'),
        ),
        migrations.AddField(
            model_name='mentrousers',
            name='uk_usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США/Великобритания'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Длина стопы (см'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='eur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Европа'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='jap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Япония'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='uk',
            field=models.CharField(blank=True, max_length=20, verbose_name='Великобритания'),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='fra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Франция'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='inter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Международный'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='ita',
            field=models.CharField(blank=True, max_length=20, verbose_name='Италия'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='jeans_waist',
            field=models.CharField(blank=True, max_length=20, verbose_name='Размер джинсов (W)'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США'),
        ),
        migrations.AlterField(
            model_name='mentrousers',
            name='waist_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Обхват бёдер (см)'),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='eur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Европа'),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='height_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='inter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Международный'),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='uk_usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США/Великобритания'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='fra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Франция'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='ger',
            field=models.CharField(blank=True, max_length=20, verbose_name='Германия'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='inter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Международный'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='ita',
            field=models.CharField(blank=True, max_length=20, verbose_name='Италия'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='uk',
            field=models.CharField(blank=True, max_length=20, verbose_name='Великобритания'),
        ),
        migrations.AlterField(
            model_name='womendressblouse',
            name='usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Длина стопы (см)'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='eur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Европа'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='jap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Япония'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='uk',
            field=models.CharField(blank=True, max_length=20, verbose_name='Великобритания'),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='fra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Франция'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='hips_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Обхват бёдер (см)'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='inter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Международный'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='ita',
            field=models.CharField(blank=True, max_length=20, verbose_name='Италия'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='jap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Япония'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='jeans_waist',
            field=models.CharField(blank=True, max_length=20, verbose_name='Размер джинсов (W)'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='uk',
            field=models.CharField(blank=True, max_length=20, verbose_name='Великобритания'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США'),
        ),
        migrations.AlterField(
            model_name='womentrousers',
            name='waist_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Обхват талии (см)'),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='eur',
            field=models.CharField(blank=True, max_length=20, verbose_name='Европа'),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='height_cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='inter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Международный'),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='rus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Россия'),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='uk_usa',
            field=models.CharField(blank=True, max_length=20, verbose_name='США/Великобритания'),
        ),
        migrations.DeleteModel(
            name='Converter',
        ),
    ]
