# Generated by Django 5.1.1 on 2024-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0003_convertiontracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertiontracker',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convertiontracker',
            name='input_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convertiontracker',
            name='input_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convertiontracker',
            name='output_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convertiontracker',
            name='output_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
