# Generated by Django 5.1.1 on 2024-10-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0004_alter_convertiontracker_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menshoes',
            name='cm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Длина стопы (см)'),
        ),
    ]
